In [2]:
import numpy as np
def matrix(n):
    if len(n)==1:
        return np.random.randint(100,size=(n[0],n[0]))
    return np.random.randint(100,size=(n[0],n[1]))

k=1 #change it as per ur requirement
l=[]
l.append(3) #change 3 as per ur requirement

In [15]:
#1.make a random nxn matrix and print it
def randmat(n):
    a=matrix(n)
    print(a)

for _ in range(k):
    randmat(l)

[[35 87  3]
 [42 82 78]
 [37 58 89]]


In [17]:
#2.sum of diagonal elements of a nxn matrix
def sumdiag(n):
    a=matrix(n)
    print(a)
    suml=0
    sumr=0
    for i in range(n[0]):
        suml+=a[i][i]
        sumr+=a[i][n[0]-i-1]
    print("sum of left diagonal:",suml)
    print("sum of right diagonal:",sumr)

for _ in range(k):
    sumdiag(l)

[[83 56 38]
 [90 61 13]
 [21 95 84]]
sum of left diagonal: 228
sum of right diagonal: 120


In [18]:
#3.add two matrices
def addmat(n):
    a=matrix(n)
    b=matrix(n)
    print(a)
    print(b)
    print(np.add(a,b))

for _ in range(k):
    addmat(l)

[[31 20 51]
 [95 94 95]
 [52 83 92]]
[[26 29 58]
 [ 1 20 17]
 [40 11 67]]
[[ 57  49 109]
 [ 96 114 112]
 [ 92  94 159]]


In [19]:
#4.element wise multiplication of 2 nxn matrices
def elemul(n):
    a=matrix(n)
    b=matrix(n)
    print(a)
    print(b)
    print(np.multiply(a,b))

for _ in range(k):
    elemul(l)

[[14 10 82]
 [22 37 43]
 [33 33 12]]
[[88 69 94]
 [87 27 67]
 [ 2 56 98]]
[[1232  690 7708]
 [1914  999 2881]
 [  66 1848 1176]]


In [20]:
#5.matrix multiplication(dot product) of 2 nxn matrices
def mulmat(n):
    a=matrix(n)
    b=matrix(n)
    print(a)
    print(b)
    print(np.dot(a,b))

for _ in range(k):
    mulmat(l)

[[28 44 74]
 [40 81 70]
 [57 63  6]]
[[39 10 26]
 [52 67 37]
 [76 43 30]]
[[ 9004  6410  4576]
 [11092  8837  6137]
 [ 5955  5049  3993]]


In [23]:
#6.rank of a matrix
def rankmat(n):
    a=matrix(n)
    print(a)
    print(np.linalg.matrix_rank(a))

for _ in range(k):
    a,b=[int(a) for a in input("Enter row and column: ").split()]
    li=[]
    li.append(a)
    li.append(b)
    rankmat(li)

[[43 25 12 45 92]
 [86 23  2 88 56]
 [62  0  3 23 69]
 [99 80 88 82 14]]
4


In [24]:
#7.trace of a nxn matrix
def trace(n):
    a=matrix(n)
    sum=0
    for i in range(n[0]):
        sum+=a[i][i]
    print(a)
    print("trace of matrix is: ",sum)

for _ in range(k):
    trace(l)

[[20 24 57]
 [59 61 69]
 [48  4 77]]
trace of matrix is:  158


In [25]:
#8.determinant of a nxn matrix
def determinant(n):
    a=matrix(n)
    print(a)
    print(np.linalg.det(a))

for _ in range(k):
    determinant(l)

[[11 32 51]
 [68 33 52]
 [32 70 38]]
133218.00000000003


In [3]:
#9.solve a set of linear equations
def equation(n):
    l=n[0]
    a=np.zeros(l*l,dtype=int)
    a=a.reshape(l,l)
    b=np.zeros(l,dtype=int)
    print("Enter the equations:")
    for i in range(l):
        print("Enter values of a1, a2,...a"+str(l),end='')
        print(" in a1x1+a2x2+...+a"+str(l)+"x"+str(l)+"=b")
        x=list(map(int,input().split()))
        for j in range(l):
            a[i][j]=x[j]
        print("Enter the b value:")
        b[i]=int(input())
    print(a)
    print(b)
    dt=np.linalg.det(a)
    if dt==0:
        print("Solution does not exist")
        return
    res=np.linalg.inv(a)
    res=np.dot(res,b)
    for i in range(l):
        print("x"+str(i+1)+": "+str(res[i]))

for _ in range(k):
    equation(l)

'''
the input may be difficult to enter
use this-
1 1 1
6
0 2 5
-4
2 5 -1
27

o/p-
5 3 -2
note that since calculation of inverse involves lot of floating point divisions answers may not be accurate to the dot
'''

Enter the equations:
Enter values of a1, a2,...a3 in a1x1+a2x2+...+a3x3=b
Enter the b value:
Enter values of a1, a2,...a3 in a1x1+a2x2+...+a3x3=b
Enter the b value:
Enter values of a1, a2,...a3 in a1x1+a2x2+...+a3x3=b
Enter the b value:
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
[ 6 -4 27]
x1: 5.000000000000002
x2: 2.9999999999999996
x3: -2.0


'\nthe input may be difficult to enter\nuse this-\n1 1 1\n6\n0 2 5\n-4\n2 5 -1\n27\n\no/p-\n5 3 -2\nnote that since calculation of inverse involves lot of floating point divisions answers may not be accurate to the dot\n'

In [33]:
#10.find mean median mode of a set of elements
def stats(a):
    n=len(a)
    sm=0
    a.sort()
    dic={}
    for i in a:
        sm+=i
        if i not in dic: dic[i]=0
        dic[i]+=1
    mean=sm/n
    median=a[n//2]
    if n%2==0:
        median=a[n//2]+a[n//2+1]
        median/=2
    max=0
    mode=0
    for i in dic.keys():
        if dic[i]>max:
            max=dic[i]
            mode=i
    print("mean: ",mean)
    print("median: ",median)
    print("mode: ",mode)

for _ in range(k+1):
    a=list(map(int,input().split()))
    print(a)
    stats(a)

[2, 3, 3, 1, 1, 1, 5, 5, 5, 5]
mean:  3.1
median:  4.0
mode:  5
[1]
mean:  1.0
median:  1
mode:  1


In [31]:
#11.row-wise max and column-wise min of nxn matrix
def maxmin(n):
    a=matrix(n)
    ma=np.zeros(n[0],dtype=np.int)
    mi=np.full(n[0],101)
    for i in range(n[0]):
        for j in range(n[0]):
            ma[i]=max(ma[i],a[i][j])
            mi[j]=min(mi[j],a[i][j])
    print(a)
    print("Row maximas are: ",ma)
    print("Column minimas are: ",mi)

for _ in range(k):
    maxmin(l)

[[10 70 12]
 [63 35 25]
 [73 53 99]]
Row maximas are:  [70 63 99]
Column minimas are:  [10 35 12]


In [32]:
#12.subtract 2 matrices
def submat(n):
    a=matrix(n)
    b=matrix(n)
    print(a)
    print(b)
    print(np.subtract(a,b))

for _ in range(k):
    submat(l)

[[ 8 41 83]
 [16  7 19]
 [82  5 12]]
[[72 57 67]
 [ 6 42 91]
 [26 22 54]]
[[-64 -16  16]
 [ 10 -35 -72]
 [ 56 -17 -42]]
